### ISSUE TITLE
Position right not animating properly

### ISSUE THREAD

**Issue by glynthink** [arkon/ng-sidebar#38]
I am positioning the '.ng-sidebar' as absolute and setting its position as 'right'.  On chrome the sidebar goes out more than it should and once i hover on it, it snaps back into its proper place.  While on firefox/other the animation is jittery.

http://imgur.com/CE6tiLt

http://imgur.com/vffjbOH

**Comment by arkon** [comment]
Hi @glynthink , I've just released v3.1.0 that makes the sidebar positioned absolutely relative to the container (instead of fixed to the entire page as it was before), so you shouldn't need to do it manually anymore.

That said, I'm not sure that fixes your problem. Did you apply any other styles to the sidebar?

**Comment by glynthink** [comment]
@arkon no other styles just that absolute positioning instead of fixed, I'm also applying position absolute on the '.ng-sidebar__backdrop'.  However my problem is still the same.

**Comment by arkon** [comment]
@glynthink Is the code available anywhere for me to check out?

**Comment by glynthink** [comment]
https://goo.gl/xKYTDH

On this page click the orange icon at the top right, tested on multiple current browsers, safari seems ok, but not any of the others

**Comment by arkon** [comment]
Interestingly, it seems to jump to the last frame a bit too quickly in Chrome Canary. In Safari, the first time it opens it has the excessive width, but subsequent opens look fine. I'm kind of wondering if these are just browser bugs. 🤔

**Comment by CatinhoCR** [comment]
Seems like this is still is not working if navbar is positioned to the right of the screen instead of left, will see if I can come up with a way to make it work and let u know..

**Comment by CatinhoCR** [comment]
I see in the demo that it gets right aligned properly, but can't figure out how to make it work... Was going to start looking into ways to fixing this and then saw in the demo it works..  but how?

**Comment by arkon** [comment]
@CatinhoCR It was a bigger mystery to me as to why it wasn't working in @glynthink's app. 😅

**Comment by CatinhoCR** [comment]
@arkon, yeah.. At first I had a little trouble understanding how to set the controls up but it's actually quite simple. Just include the control name and value into the <ng-sidebar> selector and done. Pretty neat work with this one, thanks for sharing man.
