### ISSUE TITLE
tabindex issue

### ISSUE THREAD

**Issue by vipdorian** [arkon/ng-sidebar#72]
If there more than one element with tabindex >= 0,  when the sidebar is opened a second time, tabindex is set to "-1" to all alements except first one.
To reproduce the bug, 

1. Browse to https://echeung.me/ng-sidebar/
2. Click on "Opened"
3. In Chrome inspector, change a <closesidebar=""> FOR <closesidebar="" tabindex="1">
4. Click on "This will close the sidebar too"
5 If click again on "Opened", the tabindex will be at "-1" instead of 1.

**Comment by arkon** [comment]
I actually tried setting the button to have a tabindex of 2 and the anchor with `closesidebar` to 1. They both seem fine after opening/closing multiple times. Did you do anything else too?

**Comment by vipdorian** [comment]
Hi,
see here https://www.youtube.com/watch?v=AQdweW2cXGI&feature=youtu.be

**Comment by arkon** [comment]
@vipdorian I don't think the video's permissions are set to public.

**Comment by vipdorian** [comment]
Ok, try this one  https://youtu.be/AQdweW2cXGI

2017-04-24 22:53 GMT-04:00 Eugene Cheung <notifications@github.com>:

**Comment by arkon** [comment]
@vipdorian Thanks, the video works now. I can reproduce it on my end too, so I'll be looking into this in the coming days.

**Comment by arkon** [comment]
This is actually pretty hard to reproduce consistently, but I did look over the code and made some small edits that should hopefully fix this. Feel free to reopen this if it's still happening in v4.2.2+.

**Comment by vipdorian** [comment]
Hi,
Thanks for the quick response.
I upgraded to 4.2.2 and I can reproduce it.
You can find a live example at http://ci.prescription.dorianpharmatech.com/pharmacie

I think the problem is in sidebar.component.ts at around line 411.
If the element does not have a property tabindex, it's __tabindex__ should be set to 0.
Try to change 
        if (existingTabIndex !== null) {
          el.setAttribute('__tabindex__', existingTabIndex);
        }
by
        if (existingTabIndex !== null) {
          el.setAttribute('__tabindex__', existingTabIndex);
        }
        else {
          el.setAttribute('__tabindex__', '0');
        }

*

**Comment by arkon** [comment]
I don't think explicitely setting a tabindex is correct either. After all, elements don't have it normally anyway.

**Comment by vipdorian** [comment]
Yeah you're right.
But, setting tabindex="-1" for elements which had no tabindex property is
worst. It means that elements which were tabable are not tabable anymore.

I think the solution would be : if the element did NOT have a tabindex
property, to not setting one when the sidenav is opened again.

2017-04-26 20:05 GMT-04:00 Eugene Cheung <notifications@github.com>:

**Comment by arkon** [comment]
That's intentionally done so that the elements aren't focusable when the sidebar is closed (and presumably out of the visible viewport). The current logic should already account for removing the tabindex if there was none initially.

**Comment by k-schneider** [comment]
I have a collapsible menu inside of an ng-sidebar.  When the parent items are closed I set tabindex to -1 for children:

```[attr.tabindex]="item.open ? 0 : -1"```

The sidebar appears to completely blow away any custom tabindex I'm setting though.  Is there any way to disable this behavior?

**Comment by arkon** [comment]
Yeah, it's because it removes any tabindex value assuming that it was previously set as -1 when closing the sidebar. I can probably throw together a workaround tonight.

**Comment by arkon** [comment]
@k-schneider That issue should be fixed in v7.1.0.

**Comment by k-schneider** [comment]
Thanks! But something funky is still happening if the user closes/opens the menu too quickly.  The indexes are not being restored as expected.
